{
 "title": "路由器流量监控",
 "tags": [
  "router",
  "traffic"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "主机",
    "query": {
     "query": "label_values(probpf_rx_bytes, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "路由器总体统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总下载流量",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(probpf_rx_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "总上传流量",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(probpf_tx_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "当前下载速率",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(probpf_rx_speed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "当前上传速率",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(probpf_tx_speed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "当前连接数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (host,ip,port,remote_ip,remote_port) (probpf_rx_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP连接占比",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (host,ip,port,remote_ip,remote_port) (probpf_rx_bytes{proto=\"UDP\"})) / count(count by (host,ip,port,remote_ip,remote_port) (probpf_rx_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "流量分布饼图", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Top 10 主机下载流量分布",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(probpf_rx_bytes) by (host))",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "sum(probpf_rx_bytes) - sum(topk(10, sum(probpf_rx_bytes) by (host)))",
     "legendFormat": "其他主机"
    }
   ]
  },
  {
   "title": "Top 10 主机上传流量分布",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(probpf_tx_bytes) by (host))",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "sum(probpf_tx_bytes) - sum(topk(10, sum(probpf_tx_bytes) by (host)))",
     "legendFormat": "其他主机"
    }
   ]
  },
  {
   "title": "Top 10 主机总流量分布",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(probpf_rx_bytes + probpf_tx_bytes) by (host))",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "sum(probpf_rx_bytes + probpf_tx_bytes) - sum(topk(10, sum(probpf_rx_bytes + probpf_tx_bytes) by (host)))",
     "legendFormat": "其他主机"
    }
   ]
  },
  { "title": "Top 10 主机列表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top 10 主机流量统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(probpf_rx_bytes) by (host))",
     "legendFormat": "下载统计"
    },
    {
     "expr": "topk(10, sum(probpf_tx_bytes) by (host))",
     "legendFormat": "上传统计"
    },
    {
     "expr": "topk(10, sum(probpf_rx_speed) by (host))",
     "legendFormat": "下载速率"
    },
    {
     "expr": "topk(10, sum(probpf_tx_speed) by (host))",
     "legendFormat": "上传速率"
    },
    {
     "expr": "count(count by (ip,port,remote_ip,remote_port) (probpf_rx_bytes)) by (host)",
     "legendFormat": "连接数"
    },
    {
     "expr": "count(count by (ip,port,remote_ip,remote_port) (probpf_rx_bytes{proto=\"UDP\"})) by (host) / count(count by (ip,port,remote_ip,remote_port) (probpf_rx_bytes)) by (host)",
     "legendFormat": "UDP占比"
    }
   ]
  },
  { "title": "Top 10 远程IP流量列表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Top 10 远程IP流量统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(probpf_rx_bytes) by (remote_ip,host))",
     "legendFormat": "下载统计"
    },
    {
     "expr": "topk(10, sum(probpf_tx_bytes) by (remote_ip,host))",
     "legendFormat": "上传统计"
    },
    {
     "expr": "topk(10, sum(probpf_rx_speed) by (remote_ip,host))",
     "legendFormat": "下载速率"
    },
    {
     "expr": "topk(10, sum(probpf_tx_speed) by (remote_ip,host))",
     "legendFormat": "上传速率"
    }
   ]
  }
 ]
}